### ISSUE TITLE
TODO Retextures

### ISSUE THREAD

**Issue by Drullkus** [Drullkus/Chisel-Textures#1]
Critical:
- [x] Sandstone - The shading simply is poorly done. Once they're finished, I can re-use the source files for Red Sandstone.

High Priority:
- [x] Finish Stone Bricks and Cobblestone based on [Reddit suggestions](https://www.reddit.com/r/feedthebeast/comments/4ag6bc/chisel_retexturing/). Then post a second Reddit post.
- [x] Finalize Stone Bricks and Cobblestone based on second Reddit post.
- [x] Dirt - There's a few textures that are problematic, that should be taken off of CTM V/H
- [ ] Wooden planks - There's definitely problems with Dark Oak and Acacia.
- [x] Migrate new Cobblestone Designs to the Mossy Cobblestone series.
- [x] Redstone - Some of them are just plain sloppy jobs.
- [ ] Lapis - They're just one color of blue, needs a bit of a color variation like vanilla Lapis
- [x] Glowstone - I... Don't even. Just total rehaul of coloring from re-fabricated patterns to make it more like Vanilla.
- [x] Limestone - They're not even the actual color of limestone. Limestone, in oversimplification, is literally a bone block. It's actually primarily made of Calcium that mostly comes from dead coral reefs deep underground.

Low Priority:
- [ ] Iron - They're too 'shiny' and dark compared to vanilla
- [ ] Gold - The shine can be done better, has bad color choice
- [ ] Diamond - Could be made shiner and a more vibrant color
- [ ] Emerald - Could be given a more vibrant color
- [ ] Concrete - Rename the brown Concrete to Brownstone; bring in real, gray concrete
- [ ] Netherrack - Overall needs breath-freshening. Not looking forward to the gross ones.
- [ ] Netherbrick - They don't match the vanilla netherbrick color scheme.
