### ISSUE TITLE
TODO New Textures

### ISSUE THREAD

**Issue by Drullkus** [Drullkus/Chisel-Textures#2]
- [x] Investigate potential patterns for crossing over from a block series to another
- [ ] Slime Blocks
- [x] Coal + Charcoal + Coal Coke
- [ ] Snow
- [ ] Clay + Dyed
- [ ] Grass?
- [ ] Add glass variations that are left-right blurred streaky, like Ars Magica's forcefield blocks

<sub><sub>The Technical Blocks will never end!</sub></sub>
