### ISSUE TITLE
TODO - New Patterns

### ISSUE THREAD

**Issue by Drullkus** [Drullkus/Chisel-Textures#4]
- [ ] Bouldery - Looks good on [sandstone](http://i.imgur.com/UAbg3jw.png) and [cobble](http://i.imgur.com/ZgNDKen.png)
- [x] [Some generic "quad" patterns](http://i.imgur.com/gw6deCK.png)
- [ ] This [resource pack](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/wip-resource-pack/2535492-woodpecker) has some nice [wood patterns](http://media-minecraftforum.cursecdn.com/attachments/156/584/635808385109522971.png). I didn't know how nice random-length wood looked [until now.](http://i.imgur.com/DZoDUGW.png)
